### ISSUE TITLE
Any diff between return {} and return RSVP.hash in this example?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli-todos#12]
I noticed this block in the application model hook and was curious if this was the same/or different than returning "Ember.RSVP.hash"

https://github.com/ember-cli/ember-cli-todos/blob/master/app/application/route.js#L11-L14

Thanks for the input!

**Comment by stefanpenner** [comment]
this could be refactored to use hash. it would look like:

``` js
return RSVP.hash({
  all: this.store.find('todo'),
  filter: params.state
});
```

would welcome a PR

**Comment by toranb** [comment]
Honestly I was just curious if this return RSVP.hash was needed/required/somehow better than what you had in this example app. What is the diff between these 2 solutions?

**Comment by stefanpenner** [comment]
no difference, since params.state is a value, so it doesn't ever need to wait

**Comment by toranb** [comment]
But what about the store.find ? that appears to be an async call ? What magic does RSVP.hash offer over a simple object literal when async (may or may not) be in the mix?

**Comment by stefanpenner** [comment]
> What magic does RSVP.hash offer over a simple object literal when async (may or may not) be in the mix?

if hash discovers a promise, it waits until the promise fulfills

**Comment by toranb** [comment]
Awesome! Thanks again @stefanpenner

**Comment by stefanpenner** [comment]
:)
